version: '3.2'

services:
  postgres:
    container_name: source_of_truth
    image: postgres:11.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./docker-data/postgres/data:/var/lib/postgresql/data/

  redpanda-0:
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda-0
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    - --pandaproxy-addr
    - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
    - --advertise-pandaproxy-addr
    - PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
    - --rpc-addr 0.0.0.0:33145
    - --advertise-rpc-addr redpanda-0:33145
    ports:
    - 8082:8082
    - 9092:9092
    - 28082:28082
    - 29092:29092

  redpanda-1:
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda-1
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '1'
    - --seeds "redpanda-0:33145"
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29093,OUTSIDE://localhost:9093
    - --pandaproxy-addr
    - PLAINTEXT://0.0.0.0:28083,OUTSIDE://0.0.0.0:8083
    - --advertise-pandaproxy-addr
    - PLAINTEXT://redpanda:28083,OUTSIDE://localhost:8083
    - --rpc-addr 0.0.0.0:33146
    - --advertise-rpc-addr redpanda-1:33146
    ports:
    - 8083:8083
    - 9093:9093
    - 28083:28083
    - 29093:29093

  redpanda-2:
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda-2
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '2'
    - --seeds "redpanda-0:33145"
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29094,OUTSIDE://0.0.0.0:9094
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29094,OUTSIDE://localhost:9094
    - --pandaproxy-addr
    - PLAINTEXT://0.0.0.0:28084,OUTSIDE://0.0.0.0:8084
    - --advertise-pandaproxy-addr
    - PLAINTEXT://redpanda:28084,OUTSIDE://localhost:8084
    - --rpc-addr 0.0.0.0:33147
    - --advertise-rpc-addr redpanda-2:33147
    ports:
    - 8084:8084
    - 9094:9094
    - 28084:28084
    - 29094:29094

  # topic-setup:
  #   image: docker.redpanda.com/vectorized/redpanda:latest
  #   container_name: topic-setup
  #   depends_on:
  #     - redpanda-0
  #     - redpanda-1
  #     - redpanda-2
  #   command:
  #   - topic
  #   - create
  #   - purchases
  #   - --brokers redpanda-0:9092,redpanda-1:9093,redpanda-2:9094
